# template.yml
parameters:
- name: mySteps
  type: stepList
  default: []

jobs:
- job:
  steps:
  - ${{ each step in parameters.steps }}:
    - ${{ step }}
  - ${{ if not(containsValue(parameters.steps.*.task, 'MyVirusScanner@1')) }}:
    - task: MyVirusScanner@1
      displayName: Virus scanner injected from template
