# template.yml
# (parameters identical to previous example)
jobs:
- job:
  steps:
  - ${{ each step in parameters.mySteps }}:
    - ${{ step }}
  - ${{ if not(containsValue(parameters.mySteps.*.task, 'MyVirusScanner@1')) }}:
    - task: MyVirusScanner@1
      displayName: Virus scanner injected from template
